---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: listener-operator-configmap
  labels:
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    app.kubernetes.io/version: "0.1.0-nightly"
