---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-operator-controller-deployment
  labels:
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    app.kubernetes.io/version: "0.1.0-nightly"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/role: controller
      app.kubernetes.io/name: listener-operator
      app.kubernetes.io/instance: listener-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/role: controller
        app.kubernetes.io/name: listener-operator
        app.kubernetes.io/instance: listener-operator
    spec:
      serviceAccountName: listener-operator-serviceaccount
      securityContext: {}
      containers:
        - name: listener-operator
          securityContext:
            privileged: true
            runAsUser: 0
          image: "docker.stackable.tech/stackable/listener-operator:0.1.0-nightly"
          imagePullPolicy: IfNotPresent
          resources: {}
          args:
            - run
            - controller
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: csi
              mountPath: /csi
        - name: external-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
          volumeMounts:
            - name: csi
              mountPath: /csi
      volumes:
        - name: csi
          emptyDir: {}
