---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: lb.stackable.tech
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
