---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumeclaims
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - lb.stackable.tech
    resources:
      - loadbalancerclasses
      - loadbalancers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - lb.stackable.tech
    resources:
      - loadbalancers
      - loadbalancers/status
    verbs:
      - patch
      - create
