---
apiVersion: v1
kind: Pod
metadata:
  name: example-public-pod
spec:
  volumes:
    - name: lb
      ephemeral: # <1>
        volumeClaimTemplate:
          metadata:
            annotations:
              lb.stackable.tech/lb-class: public # <2>
          spec:
            storageClassName: lb.stackable.tech
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: "1"
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: lb
          mountPath: /lb # <3>
