= `LoadBalancerClass`

A `LoadBalancerClass` defines a category of load balancers. For example, this could be "VPC-internal service", "internet-accessible service", or "K8s-internal service".
The `LoadBalancerClass` then defines how this intent is realized in a given cluster.

For example, a Google Kubernetes Engine (GKE) cluster might want to expose all internet-facing services using a xref:loadbalancer.adoc[], since GKE nodes are
relatively short-lived and don't have stable addresses:

[source,yaml]
----
include::example$lbclass-public-gke.yaml[]
----

On the other hand, an on-premise cluster might not have dedicated load balancer infrastructure at all, but has "pet" Nodes with lifetimes on the orders
of years. This might lead administrators of such systems to prefer exposing node ports directly instead:

[source,yaml]
----
include::example$lbclass-public-onprem.yaml[]
----

Finally, it can be desirable to add additional annotations to a `Service`. For example, a user might want to only expose some services inside a given cloud vendor VPC. How exactly this is accomplished depends on the cloud provider in question, but for GKE this requires the annotation `networking.gke.io/load-balancer-type`:

[source,yaml]
----
include::example$lbclass-internal-gke.yaml[]
----
