= Installation

There are two ways to run the Stackable Listener Operator:

. Helm managed Docker container deployment on Kubernetes
. Build from source

== Prerequisites

You will need:

* a Kubernetes cluster
* kubectl
* Helm

Resource sizing depends on cluster type(s), usage and scope, but as a starting point we recommend a minimum of the following resources for this operator:

* 0.2 cores (e.g. i5 or similar)
* 256MB RAM

== Helm
Helm allows you to download and deploy Stackable operators on Kubernetes and is by far the easiest installation method. First ensure that you have installed the Stackable Operators Helm repository:

[source,console]
----
$ helm repo add stackable https://repo.stackable.tech/repository/helm-stable/
----

Then install the Stackable Listener Operator

[source,console]
----
$ helm install listener-operator stackable/listener-operator
----

Helm will deploy the operator in Kubernetes containers and apply the CRDs.
You're now ready to expose services!

=== Microk8s

Microk8s uses a non-standard Kubelet state directory.
Installing listener-operator on Microk8s requires the argument
`--set kubeletDir=/var/snap/microk8s/common/var/lib/kubelet` to be added to the `helm install` command.
