= ListenerClass
:description: The ListenerClass defines listener types and exposure rules for Kubernetes Pods, supporting various service types like ClusterIP, NodePort, and LoadBalancer.

A ListenerClass defines a category of listeners.
For example, this could be "VPC-internal service", "internet-accessible service", or "K8s-internal service".
The ListenerClass then defines how this intent is realized in a given cluster.

For example, a Google Kubernetes Engine (GKE) cluster might want to expose all internet-facing services using a managed load balancer, since GKE nodes are
relatively short-lived and don't have stable addresses:

[source,yaml]
----
include::example$listenerclass-public-gke.yaml[]
----

On the other hand, an on-premise cluster might not have dedicated load balancer infrastructure at all, but instead use "pet" Nodes which may be expected to live for years.
This might lead administrators of such systems to prefer exposing node ports directly instead:

[source,yaml]
----
include::example$listenerclass-public-onprem.yaml[]
----

Finally, it can be desirable to add additional annotations to a Service.
For example, a user might want to only expose some services inside a given cloud vendor VPC.
How exactly this is accomplished depends on the cloud provider in question, but for GKE this requires the annotation `networking.gke.io/load-balancer-type`:

[source,yaml]
----
include::example$listenerclass-internal-gke.yaml[]
----

[#servicetype]
== Service types

The service type is defined by `ListenerClass.spec.serviceType`.
The following service types are currently supported by the Stackable Listener Operator:

[#servicetype-clusterip]
=== `ClusterIP`

The Listener can be accessed from inside the Kubernetes cluster.
The Listener addresses will direct clients to the cluster-internal address.

[#servicetype-nodeport]
=== `NodePort`

The Listener can be accessed from outside the Kubernetes cluster.
This may include the internet, if the Nodes have public IP addresses.
The Listener address will direct clients to connect to a randomly assigned port on the Nodes running the Pods.

Additionally, Pods bound to `NodePort` listeners will be xref:volume.adoc#pinning[pinned] to a specific Node.
If this is undesirable, consider using xref:#servicetype-loadbalancer[] instead.

[#servicetype-loadbalancer]
=== `LoadBalancer`

The Listener can be accessed from outside the Kubernetes cluster.
This may include the internet, depending on the configuration of the Kubernetes cloud controller manager.
A dedicated address will be allocated for the Listener.

Compared to xref:#servicetype-nodeport[], this service type allows Pods to be moved freely between Nodes.
However, it requires https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[a cloud controller manager that supports load balancers].
Additionally, many cloud providers charge for load-balanced traffic.

[#servicetype-loadbalancer-class]
==== Custom load-balancer classes

Kubernetes supports using multiple different load balancer types in the same cluster by configuring a unique https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class[load-balancer class] for each provider.

The Stackable Listener Operator supports using custom classes setting the `ListenerClass.spec.loadBalancerClass`.

NOTE: `loadBalancerClass` is _only_ respected when using the xref:#servicetype-loadbalancer[] service type. Otherwise, the field will be ignored.

[#addresstype]
== Address types

The Stackable Listener Operator supports both IP addresses and DNS hostnames. The preferred address type for a given ListenerClass can be configured using the `ListenerClass.spec.preferredAddressType` field. If no `preferredAddressType` is specified then it defaults to xref:#addresstype-hostname-conservative[].

NOTE: If the preferred address type is not supported for a given environment then another type will be used.

[#addresstype-ip]
=== IP

The IP address of a resource. The addresses will be less predictable (especially for xref:#servicetype-clusterip[] services),
but does not require any special client configuration (beyond what the xref:#servicetype[] requires).

[#addresstype-hostname]
=== Hostname

The DNS hostname of a resource. Clients must be able to resolve these addresses in order to connect, which may require special DNS configuration.

[#addresstype-hostname-conservative]
=== HostnameConservative

A pseudo-addresstype that is equivalent to xref:#addresstype-ip[] for xref:#servicetype-nodeport[] services, and xref:#addresstype-hostname[] for all others.
This means that we default to hostnames where "safe", but don't assume that nodes are resolvable by external clients.

== Default ListenerClasses

The Stackable Data Platform assumes the existence of a few predefined ListenerClasses, and will use them by default as appropriate:

`cluster-internal`:: Used for listeners that are only accessible internally from the cluster. For example: communication between ZooKeeper nodes.
`external-unstable`:: Used for listeners that are accessible from outside the cluster, but which do not require a stable address. For example: individual Kafka brokers.
`external-stable`:: Used for listeners that are accessible from outside the cluster, and do require a stable address. For example: Kafka bootstrap.

=== Presets

To help users get started, the Stackable Listener Operator ships different ListenerClass _presets_ for different environments.
These are configured using the `preset` Helm value.

[#preset-stable-nodes]
==== `stable-nodes`

The `stable-nodes` preset installs ListenerClasses appropriate for Kubernetes clusters that use long-lived "pet nodes".
This does _not_ require any particular networking setup, but makes pods that require
stable addresses "sticky" to the Kubernetes Node that they were scheduled to.
In addition, downstream operators may generate configurations that refer to particular nodes by name.

The following ListenerClasses are installed:

`cluster-internal`:: xref:#servicetype-clusterip[]
`external-unstable`:: xref:#servicetype-nodeport[]
`external-stable`:: xref:#servicetype-nodeport[]

[#preset-ephemeral-nodes]
==== `ephemeral-nodes`

The `ephemeral-nodes` preset installs ListenerClasses appropriate for Kubernetes clusters that use short-lived "cattle nodes".
This makes them appropriate for managed cloud environments, but requires that
a LoadBalancer controller is present in the cluster.

Managed cloud environments should generally already provide an integrated LoadBalancer controller.
For on-premise environments, an external implementation such as https://docs.tigera.io/calico/latest/networking/configuring/advertise-service-ips[Calico] or https://metallb.org/[MetalLB] can be used.

NOTE: K3s' built-in https://docs.k3s.io/networking#service-load-balancer[ServiceLB] (Klipper) is _not_ recommended, because it doesn't allow multiple Services to bind the same Port.
If you use ServiceLB, use the xref:#preset-stable-nodes[] preset instead.

The following ListenerClasses are installed:

`cluster-internal`:: xref:#servicetype-clusterip[]
`external-unstable`:: xref:#servicetype-nodeport[]
`external-stable`:: xref:#servicetype-loadbalancer[]

[#preset-none]
==== `none`

The `none` (pseudo-)preset installs no ListenerClasses, leaving the administrator to define them for themself.
