= `ListenerClass`

A `ListenerClass` defines a category of listeners. For example, this could be "VPC-internal service", "internet-accessible service", or "K8s-internal service".
The `ListenerClass` then defines how this intent is realized in a given cluster.

For example, a Google Kubernetes Engine (GKE) cluster might want to expose all internet-facing services using a managed load balancer, since GKE nodes are
relatively short-lived and don't have stable addresses:

[source,yaml]
----
include::example$listenerclass-public-gke.yaml[]
----

On the other hand, an on-premise cluster might not have dedicated load balancer infrastructure at all, but instead use "pet" Nodes which may be expected to live for years. This might lead administrators of such systems to prefer exposing node ports directly instead:

[source,yaml]
----
include::example$listenerclass-public-onprem.yaml[]
----

Finally, it can be desirable to add additional annotations to a `Service`. For example, a user might want to only expose some services inside a given cloud vendor VPC. How exactly this is accomplished depends on the cloud provider in question, but for GKE this requires the annotation `networking.gke.io/load-balancer-type`:

[source,yaml]
----
include::example$listenerclass-internal-gke.yaml[]
----

== Service types

The service type is defined by `ListenerClass.spec.serviceType`. The following service types are currently supported by the Stackable Listener Operator:

[#servicetype-clusterip]
=== `ClusterIP`

The listener can be accessed from inside of the Kubernetes cluster. The listener addresses will direct clients to the cluster-internal address.

[#servicetype-nodeport]
=== `NodePort`

The listener can be accessed from outside the Kubernetes cluster. The listener address will direct clients to connect to a randomĺy assigned port on the nodes running the pods.

Additionally, pods bound to `NodePort` listeners will be xref:volume.adoc#pinning[pinned] to a specific node. If this is undesirable, consider using xref:#servicetype-loadbalancer[] instead.

[#servicetype-loadbalancer]
=== `LoadBalancer`

The listener can be accessed from outside the Kubernetes cluster. A dedicated address will be allocated for the listener, which any clients will be directed to connect to using.

Compared to xref:#servicetype-nodeport[], this service type allows pods to be moved freely between nodes. However, it requires https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[a cloud controller manager that supports load balancers]. Additionally, many cloud providers charge for load-balanced traffic.
