= ListenerClass

A ListenerClass defines a category of listeners. For example, this could be "VPC-internal service", "internet-accessible service", or "K8s-internal service".
The ListenerClass then defines how this intent is realized in a given cluster.

For example, a Google Kubernetes Engine (GKE) cluster might want to expose all internet-facing services using a managed load balancer, since GKE nodes are
relatively short-lived and don't have stable addresses:

[source,yaml]
----
include::example$listenerclass-public-gke.yaml[]
----

On the other hand, an on-premise cluster might not have dedicated load balancer infrastructure at all, but instead use "pet" Nodes which may be expected to live for years. This might lead administrators of such systems to prefer exposing node ports directly instead:

[source,yaml]
----
include::example$listenerclass-public-onprem.yaml[]
----

Finally, it can be desirable to add additional annotations to a Service. For example, a user might want to only expose some services inside a given cloud vendor VPC. How exactly this is accomplished depends on the cloud provider in question, but for GKE this requires the annotation `networking.gke.io/load-balancer-type`:

[source,yaml]
----
include::example$listenerclass-internal-gke.yaml[]
----

== Service types

The service type is defined by `ListenerClass.spec.serviceType`. The following service types are currently supported by the Stackable Listener Operator:

[#servicetype-clusterip]
=== `ClusterIP`

The Listener can be accessed from inside the Kubernetes cluster. The Listener addresses will direct clients to the cluster-internal address.

[#servicetype-nodeport]
=== `NodePort`

The Listener can be accessed from outside the Kubernetes cluster. This may include the internet, if the Nodes have public IP addresses. The Listener address will direct clients to connect to a randomly assigned port on the Nodes running the Pods.

Additionally, Pods bound to `NodePort` listeners will be xref:volume.adoc#pinning[pinned] to a specific Node. If this is undesirable, consider using xref:#servicetype-loadbalancer[] instead.

[#servicetype-loadbalancer]
=== `LoadBalancer`

The Listener can be accessed from outside the Kubernetes cluster. This may include the internet, depending on the configuration of the Kubernetes cloud controller manager. A dedicated address will be allocated for the Listener.

Compared to xref:#servicetype-nodeport[], this service type allows Pods to be moved freely between Nodes. However, it requires https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[a cloud controller manager that supports load balancers]. Additionally, many cloud providers charge for load-balanced traffic.

== Default ListenerClasses

The Stackable Data Platform assumes the existence of a few predefined ListenerClasses, and will use them by default as appropriate:

`cluster-internal`:: Used for listeners that are only accessible internally from the cluster. For example: communication between ZooKeeper nodes.
`external-unstable`:: Used for listeners that are accessible from outside of the cluster, but which do not require a stable address. For example: individual Kafka brokers.
`external-stable`:: Used for listener that are accessible from outside of the cluster, and do require a stable address. For example: Kafka bootstrap.

=== Presets

To help users get started, the Stackable Listener Operator ships different ListenerClass _presets_ for different environments. These are configured using the `preset` Helm value.

[#preset-pets]
==== `pets`

The `pets` preset installs ListenerClasses appropriate for Kubernetes clusters that use long-lived "pet nodes". This does _not_ require any particular networking setup, but makes pods that require
stable addresses "sticky" to the Kubernetes Node that they were scheduled to. In addition, downstream operators may generate configurations that refer to particular nodes by name.

The following ListenerClasses are installed:

`cluster-internal`:: xref:#servicetype-clusterip[]
`external-unstable`:: xref:#servicetype-nodeport[]
`external-stable`:: xref:#servicetype-nodeport[]

[#preset-cattle]
==== `cattle`

The `cattle` preset installs ListenerClasses appropriate for Kubernetes clusters that use short-lived "cattle nodes". This makes them appropriate for managed cloud environments, but requires that
a LoadBalancer controller is present in the cluster.

The following ListenerClasses are installed:

`cluster-internal`:: xref:#servicetype-clusterip[]
`external-unstable`:: xref:#servicetype-nodeport[]
`external-stable`:: xref:#servicetype-loadbalancer[]

[#preset-none]
==== `none`

The `none` (pseudo-)preset installs no ListenerClasses, leaving the administrator to define them for themself.
