---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exposed-nginx-nodeport
spec:
  replicas: 1
  serviceName: ""
  selector:
    matchLabels:
      app: exposed-nginx-nodeport
  template:
    metadata:
      labels:
        app: exposed-nginx-nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: listener
          mountPath: /usr/share/nginx/html/listener
        - name: tls
          mountPath: /tls
        - name: listener2
          mountPath: /usr/share/nginx/html/listener2
      volumes:
        - name: tls
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  secrets.stackable.tech/class: tls
                  secrets.stackable.tech/scope: listener=listener,listener=listener2
              spec:
                storageClassName: secrets.stackable.tech
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: "1"
        - name: listener2
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  listeners.stackable.tech/listener-class: nodeport
              spec:
                accessModes:
                - ReadWriteMany
                storageClassName: listeners.stackable.tech
                resources:
                  requests:
                    storage: 1
  volumeClaimTemplates:
  - metadata:
      name: listener
      annotations:
        listeners.stackable.tech/listener-class: nodeport
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: listeners.stackable.tech
      resources:
        requests:
          storage: 1
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls-manual
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: foo
  labels:
    secrets.stackable.tech/class: tls-manual
    secrets.stackable.tech/node: kind-control-plane
    secrets.stackable.tech/listener.0: listener-exposed-nginx-nodeport-0
    secrets.stackable.tech/listener.1: exposed-nginx-nodeport-0-listener2
stringData:
  foo: bar
