---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exposed-nginx-lb
spec:
  replicas: 1
  serviceName: ""
  selector:
    matchLabels:
      app: exposed-nginx-lb
  template:
    metadata:
      labels:
        app: exposed-nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 9999
        volumeMounts:
        - name: listener
          mountPath: /usr/share/nginx/html/listener
        - name: config
          mountPath: /etc/nginx/templates
      volumes:
      - name: config
        configMap:
          name: exposed-nginx-lb-config
  volumeClaimTemplates:
  - metadata:
      name: listener
      annotations:
        listeners.stackable.tech/listener-class: lb-external
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: listeners.stackable.tech
      resources:
        requests:
          storage: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exposed-nginx-lb-config
data:
  default.conf.template: |
    server {
        listen       9999;
        listen  [::]:9999;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
