---
{{- with .Values.csiNodeDriver }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "operator.fullname" $ }}-csi-node-driver
  labels:
    {{- include "operator.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/role: node-driver
      {{- include "operator.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/role: node-driver
        {{- include "operator.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.fullname" $ }}-serviceaccount
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: csi-node-service
          securityContext:
            {{- toYaml .nodeService.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            {{ .nodeService.resources | toYaml | nindent 12 }}
          args:
            - run
            - node
          env:
            # The following env vars are passed as clap (think CLI) arguments to the operator.
            # They are picked up by clap using the structs defied in the operator.
            # (which is turn pulls in https://github.com/stackabletech/operator-rs/blob/main/crates/stackable-operator/src/cli.rs)
            # You can read there about the expected values and purposes.

            - name: CSI_ENDPOINT
              value: /csi/csi.sock

            # Sometimes products need to know the operator image, e.g. the opa-bundle-builder OPA
            # sidecar uses the operator image.
            - name: OPERATOR_IMAGE
              # Tilt can use annotations as image paths, but not env variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['internal.stackable.tech/image']

            # Namespace the operator Pod is running in, e.g. used to construct the conversion
            # webhook endpoint.
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            # The name of the Kubernetes Service that point to the operator Pod, e.g. used to
            # construct the conversion webhook endpoint.
            - name: OPERATOR_SERVICE_NAME
              value: {{ include "operator.fullname" $ }}

            # Operators need to know the node name they are running on, to e.g. discover the
            # Kubernetes domain name from the kubelet API.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            {{- if $.Values.kubernetesClusterDomain }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ $.Values.kubernetesClusterDomain | quote }}
            {{- end }}
            {{- include "telemetry.envVars" $ | nindent 12 }}
          volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: {{ $.Values.kubeletDir }}/pods
        - name: node-driver-registrar
          image: "{{ .nodeRegistrar.image.repository }}:{{ .nodeRegistrar.image.tag }}"
          imagePullPolicy: {{ .nodeRegistrar.image.pullPolicy }}
          resources:
            {{ .nodeRegistrar.resources | toYaml | nindent 12 }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ $.Values.kubeletDir }}/plugins/listeners.stackable.tech/csi.sock
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
      volumes:
        - name: registration-sock
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            # see https://github.com/stackabletech/secret-operator/issues/229 for why this path should not be too long
            path: {{ $.Values.kubeletDir }}/plugins_registry
        - name: csi
          hostPath:
            path: {{ $.Values.kubeletDir }}/plugins/listeners.stackable.tech/
        - name: mountpoint
          hostPath:
            path: {{ $.Values.kubeletDir }}/pods/
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
