---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "operator.fullname" . }}-node-daemonset
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/role: node
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/role: node
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.fullname" . }}-serviceaccount
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "operator.appname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ .Values.node.driver.resources | toYaml | nindent 12 }}
          args:
            - run
            - node
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock

            # Operators need to know the node name they are running on, to e.g. discover the
            # Kubernetes domain name from the kubelet API.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            {{- if .Values.kubernetesClusterDomain }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ .Values.kubernetesClusterDomain | quote }}
            {{- end }}
            {{- include "telemetry.envVars" . | nindent 12 }}
          volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: {{ .Values.kubeletDir }}/pods
        - name: node-driver-registrar
          image: "{{ .Values.csiNodeDriverRegistrar.image.repository }}:{{ .Values.csiNodeDriverRegistrar.image.tag }}"
          imagePullPolicy: {{ .Values.csiNodeDriverRegistrar.image.pullPolicy }}
          resources:
            {{ .Values.csiNodeDriverRegistrar.resources | toYaml | nindent 12 }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.kubeletDir }}/plugins/listeners.stackable.tech/csi.sock
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
      volumes:
        - name: registration-sock
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            # see https://github.com/stackabletech/secret-operator/issues/229 for why this path should not be too long
            path: {{ .Values.kubeletDir }}/plugins_registry
        - name: csi
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins/listeners.stackable.tech/
        - name: mountpoint
          hostPath:
            path: {{ .Values.kubeletDir }}/pods/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
